# Generated by Django 2.2.17 on 2021-03-23 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20210316_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 19, 48, 40, 43905, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
